* My NixOS and environment management
This repository manages nix files for my NixOS-machine (in the future), and home directory management for some hosts.

* Managed environment

- *Ereshkigal* :: My main machine. It's NixOS.
- *my-gentoo* :: My old gentoo machine. It's only managed home directory. (Remove future)


* File structure

** home-manager
Locate modules for home-manager and daily use programs.

- *cli* :: management for CLI in daily use, such as git, starship, fish and more.
- *cli/fish* :: Fish configuration files.
- *gui* :: managemtn for GUI applications. Such as hyprland on Linux.
- *gui/emacs* :: My main editor is Emacs, so I manage it in nix.


** modules
~modules~ manages *system-global* managemnet. So it is used for NixOS only.

** pkgs
~pkgs~ defines private packages. Such as kernel modules, custom fcitx5, or fonts to use with Emacs/Terminal.

* develop

** for OS
#+begin_src shell
  $ nix develop
  $ nh os switch .

  # If you already on NixOS, you can call nh on your environment.
  $ nh os switch .
#+end_src

** for Home
#+begin_src shell
  $ nix develop
  $ nix home switch .
#+end_src
